# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: registry.csplab.cloudns.cx/microprofile/customer-mp
  tag: v1.0.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi

service:
  name: customer
  cloudantservicename: cloudant-service
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443

services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100

jwt:
  id: myMpJwt
  uri: https://auth-service:9443/oidc/endpoint/OP/jwk
  issuer: https://auth-service:9443/oidc/endpoint/OP

cloudant:
  user: admin
  password: pass
  protocol: http
  host: localhost
  port: 80
  database: customers

## Persist data to a persistent volume
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "glusterfs"
  accessMode: ReadWriteOnce
